import os
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT_DIR / "data"

FULL_TEXT_CHAR_LIMIT = int(os.environ.get("FULL_TEXT_CHAR_LIMIT", 80_000))
BATCH_BUILD_PROFILES_MAX_WORKERS = int(os.environ.get("BATCH_BUILD_PROFILES_MAX_WORKERS", 2))
BATCH_INGEST_MAX_WORKERS = int(os.environ.get("BATCH_INGEST_MAX_WORKERS", 5))
WORKFLOW_MAX_PAPERS = int(os.environ.get("WORKFLOW_MAX_PAPERS", 12))
ARXIV_SEARCH_TIMEOUT = int(os.environ.get("ARXIV_SEARCH_TIMEOUT", 30))
SEMANTIC_SCHOLAR_TIMEOUT = int(os.environ.get("SEMANTIC_SCHOLAR_TIMEOUT", 30))
PDF_DOWNLOAD_TIMEOUT = int(os.environ.get("PDF_DOWNLOAD_TIMEOUT", 60))
LLM_REQUEST_TIMEOUT = int(os.environ.get("LLM_REQUEST_TIMEOUT", 300))
EXTRACT_FIELD_TIMEOUT = int(os.environ.get("EXTRACT_FIELD_TIMEOUT", 90))
EXTRACT_INSIGHTS_TIMEOUT = int(os.environ.get("EXTRACT_INSIGHTS_TIMEOUT", 90))
BUILD_PROFILE_TIMEOUT = int(os.environ.get("BUILD_PROFILE_TIMEOUT", 600))
ANALYZE_PAPERS_TIMEOUT = int(os.environ.get("ANALYZE_PAPERS_TIMEOUT", 90))
DETECT_GAPS_TIMEOUT = int(os.environ.get("DETECT_GAPS_TIMEOUT", 300))
SUGGEST_EXPERIMENTS_TIMEOUT = int(os.environ.get("SUGGEST_EXPERIMENTS_TIMEOUT", 300))
LLM_TEMPERATURE = float(os.environ.get("LLM_TEMPERATURE", "0.0"))
IONOS_API_TOKEN = os.environ.get("IONOS_API_TOKEN", "")
IONOS_BASE_URL = os.environ.get("IONOS_BASE_URL", "").rstrip("/")
IONOS_MODEL = os.environ.get("IONOS_MODEL", "")
S2_API_KEY = os.environ.get("S2_API_KEY")
